### ISSUE TITLE
isTablet() Returns Wrong Value for iPad (5th generation) 

### ISSUE THREAD

**Issue by Pczek** [rebeccahughes/react-native-device-info#326]
## Summary
DeviceInfo.isTablet() returns wrong value for "iPad (5th generation)" Simulator. May be true for real device as well. 
The Library uses a Configuration for Android Screen Sizes to detect if the device is a tablet. This is results in the wrong value. How about we split the detection for Android and iOS in order to tackle this issue. For now at least iPads have a different aspect ratio as iPhones. This could be used to detect iOS tablets at least. Not sure if it's true for Android devices.

## Current behavior

DeviceInfo.isTablet() returns FALSE for iPad (5th generation) 

## Expected behavior

DeviceInfo.isTablet() returns TRUE for iPad (5th generation)

**Comment by machour** [comment]
Hi @Pczek,

The Android and iOS detections are completely separated unless I'm missing something.
Here's [how we do it](https://github.com/rebeccahughes/react-native-device-info/blob/master/RNDeviceInfo/RNDeviceInfo.m#L200) for iOS:

```objective-c
- (bool) isTablet
{
  return [[UIDevice currentDevice] userInterfaceIdiom] == UIUserInterfaceIdiomPad;
}
```

**Comment by machour** [comment]
Closing this issue as no feedback was provided. 
Feel free to open it again if the problem still happens

**Comment by kashifsulaiman** [comment]
@machour same issue with IOs only. I've tried at many Ipad emulators, isTablet is returning false, while working as expected on android

**Comment by ertejaspatel** [comment]
Is there any solutions for how to get correct value for ipad?

**Comment by mikehardy** [comment]
Huh. I just checked this on a tablet emulator and sure enough, the example returns false for this tablet! However, I noticed the UI was doing the phone-locked UI thing where I could expand it etc, but it was not using the iPad like a tablet.

When I changed the build from "iPhone" to "Universal" in the General -> Deployment Info area of XCode for the example, it worked - isTablet() returned true.

So this may be a build-setting thing. You can tell from getDeviceId() that your hardware is an iPad, so you can use that for a device check, but isTablet only returns true if the UI is actually running like a tablet. I think that's fair enough.

**Comment by fukemy** [comment]
Hi, any new solution?

**Comment by mikehardy** [comment]
@fukemy well, in the 3+ years since the last comment, no one else has posted a comment, and github does not have a secret comments mode I'm aware of, so nope, no new updates or solutions.

But since you've generated notifications on this repo and I do my best to maintain it so I had to read your notification...

I will say the general idea of "isTablet" is not a great idea in the modern world. You want to use responsive break points and check screen width dp to render either a small UI, medium UI, large UI, etc. Search responsive design and use something like https://github.com/react-native-community/hooks#usedimensions to dynamically re-layout as needed.
