### ISSUE TITLE
Google Pixel C returned isTablet = false

### ISSUE THREAD

**Issue by Ken-Lim** [rebeccahughes/react-native-device-info#369]
## Google Pixel C returned isTablet = false

|             |     |
| ----------- | --- |
| Version     |  0.21.2  |
| Affected OS | Android  |
| OS Version  | 8.0.0   |

## Current behavior
IsTablet is returning false for Google Pixel C (emulator), don't have actual device to test out.
## Expected behavior
IsTablet should return true.

**Comment by machour** [comment]
Hi @Ken-Lim and thank you for reporting this. How would you define a tablet?

The problem is: there's actually no accurate way on Android to guess if a device is a Phone or a Tablet. See also https://github.com/rebeccahughes/react-native-device-info/issues/198#issuecomment-362791408

The only accurate way I can think of if to manually handle a list of tablets, but that would be unrealistic regarding the vast number of vendors worldwide.

Feel free to send a PR if you find a better implementation.

**Comment by dvshub** [comment]
This page seems helpful, defining the aspect ratios and height/width in px and dp, covering most of the device categories out there - https://material.io/tools/devices/
The first column "Type" specifies whether the device is considered a tablet or not.

**Comment by machour** [comment]
I guess it's fair enough to assume this is fixed, thank you for getting back to me.
@Ken-Lim please re-open if you still see the problem with 0.26.1
