### ISSUE TITLE
Implementation issue in v0.24.3

### ISSUE THREAD

**Issue by dozel** [rebeccahughes/react-native-device-info#523]
## Summary

| ----------- | --- |
| Version     |  0.24.3 |
| Affected OS | android   |
| OS Version  | mac v10   |

## Current behavior
Building android project quickly fails with:
Error:(29, 1) A problem occurred evaluating project ':react-native-device-info'.
> Could not find method implementation() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

## Expected behavior
I expected the android project to build.

I saw some of the PRs that went into making sure RN .57 would work with this library, and I thought I upgraded to the right version (0.24.3). Is there anything else I need to do to make it work?

Thanks!

**Comment by sonicdoe** [comment]
Which version of the Android Gradle plugin are you using? `implementation` (instead of `compile`) is only available in v3.0.0 and later.

**Comment by dozel** [comment]
You were right, thank you!

**Comment by Wuguanghua** [comment]
my geadle version is 2.14 ，as @sonicdoe said: implementation (instead of compile) is only available in v3.0.0 and later.
so i can not ues this solution .
 
my solution:
 1.  go to file `/node_modules/react-native-device-info/android/build.gradle`
 2. Replace `implementation` with `compile` 


before:


<img width="752" alt="2018-11-07 5 53 19" src="https://user-images.githubusercontent.com/28554105/48126977-9f0e2200-e2bd-11e8-97a8-7bddd6e66cfe.png">
 after:

<img width="752" alt="2018-11-07 5 53 32" src="https://user-images.githubusercontent.com/28554105/48127039-be0cb400-e2bd-11e8-8140-43a747c7212d.png">

 3. `react-native run-android`

it work for me !!!

**Comment by machour** [comment]
Or stick to 0.24.2 :)
